---
- hosts: tag_service_docker
  become: true

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  pre_tasks:
    - name: Install python3-pip and docker-compose package
      apt:
        name:
        - python3-pip
        - docker-compose
        state: present
        update_cache: yes

  tasks:
    - name: Creates directory
      file:
        path: /opt/timezoneapp
        state: directory

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src:  files/docker-compose.yml
        dest: /opt/timezoneapp/docker-compose.yml
        owner: admin
        group: admin
        mode: '0644'
    - name: Make sure docker service is running
      service:
        name: docker
        state: started

    - name: Run docker compose
      community.docker.docker_compose:
        project_src: /opt/timezoneapp
        state: present
